---
- name: Ensure Architecture
  foreman_architecture:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    foreman_host: '{{ foreman_host }}'
    foreman_port: '{{ foreman_port }}'
    foreman_user: '{{ foreman_user }}'
    foreman_pass: '{{ foreman_pass }}'
  with_items: foreman_architectures
  tags: foreman_architecture
  register: foreman_architecture_result

- debug: var=foreman_architecture_result.results
  when: foreman_debug
