---
- name: Ensure Compute Resource
  foreman_compute_resource:
    name: '{{ item.name }}'
    datacenter: '{{ item.datacenter | default(omit) }}'
    provider: '{{ item.provider | default(omit) }}'
    password: '{{ item.password | default(omit) }}'
    server: '{{ item.server | default(omit) }}'
    state: '{{ item.state }}'
    url: '{{ item.url | default(omit) }}'
    user: '{{ item.user | default(omit) }}'
    foreman_host: '{{ foreman_host }}'
    foreman_port: '{{ foreman_port }}'
    foreman_user: '{{ foreman_user }}'
    foreman_pass: '{{ foreman_pass }}'
  with_items: foreman_compute_resources
  tags: foreman_compute_resource
  register: foreman_compute_resource_result

- debug: var=foreman_compute_resource_result.results
  when: foreman_debug
