---
- name: Ensure Config Template
  foreman_config_template:
    name: '{{ item.name }}'
    locked: '{{ item.locked | default(omit) }}'
    operatingsystems: '{{ item.operatingsystems | default(omit) }}'
    template: '{{ item.template | default(omit) }}'
    template_file: '{{ item.template_file | default(omit) }}'
    template_kind_name: '{{ item.template_kind_name | default(omit) }}'
    snippet: '{{ item.snippet | default(omit) }}'
    state: '{{ item.state }}'
    foreman_host: '{{ foreman_host }}'
    foreman_port: '{{ foreman_port }}'
    foreman_user: '{{ foreman_user }}'
    foreman_pass: '{{ foreman_pass }}'
  with_items: foreman_config_templates
  register: foreman_config_template_result

- debug: var=foreman_config_template_result.results
  when: foreman_debug
