---
- name: Ensure Domain
  foreman_domain:
    name: '{{ item.name }}'
    dns_proxy: '{{ item.dns_proxy }}'
    state: '{{ item.state }}'
    foreman_host: '{{ foreman_host }}'
    foreman_port: '{{ foreman_port }}'
    foreman_user: '{{ foreman_user }}'
    foreman_pass: '{{ foreman_pass }}'
  with_items: foreman_domains
  tags: foreman_domain
  register: foreman_domain_result

- debug: var=foreman_domain_result.results
  when: foreman_debug
