---
- name: Ensure Hostgroup
  foreman_hostgroup:
    name: '{{ item.name }}'
    architecture: '{{ item.architecture | default(None) }}'
    compute_profile: '{{ item.compute_profile | default(None) }}'
    domain: '{{ item.domain | default(None) }}'
    environment: '{{ item.environment | default(None) }}'
    medium: '{{ item.medium | default(None) }}'
    operatingsystem: '{{ item.operatingsystem | default(None) }}'
    partition_table: '{{ item.partition_table | default(None) }}'
    subnet: '{{ item.subnet | default(None) }}'
    state: '{{ item.state | default(None) }}'
    foreman_host: '{{ foreman_host }}'
    foreman_port: '{{ foreman_port }}'
    foreman_user: '{{ foreman_user }}'
    foreman_pass: '{{ foreman_pass }}'
  with_items: foreman_hostgroups
  register: foreman_hostgroup_result

- debug: var=foreman_hostgroup_result.results
  when: foreman_debug
