---
- name: Ensure host
  foreman_host:
    name: '{{ item.name }}'
    architecture: '{{ item.architecture | default(foreman_default_architecture) }}'
    build: '{{ item.build | default(foreman_default_build) | default(omit) }}'
    compute_profile: '{{ item.compute_profile | default(foreman_default_compute_profile) | default(omit) }}'
    compute_resource: '{{ item.compute_resource | default(foreman_default_compute_resource) | default(omit) }}'
    domain: '{{ item.domain | default(foreman_default_domain) | default(omit) }}'
    enabled: '{{ item.enabled | default(foreman_default_enabled) | default(omit) }}'
    environment: '{{ item.environment | default(foreman_default_environment) | default(omit) }}'
    hostgroup: '{{ item.hostgroup | default(foreman_default_hostgroup) | default(omit) }}'
    image: '{{ item.image | default(foreman_default_image) | default(omit) }}'
    location: '{{ item.location | default(foreman_default_location) | default(omit) }}'
    managed: '{{ item.managed | default(foreman_default_managed) | default(omit) }}'
    medium: '{{ item.medium | default(foreman_default_medium ) | default(omit) }}'
    operatingsystem: '{{ item.operatingsystem | default(foreman_default_operatingsystem) | default(omit) }}'
    organization: '{{ item.organization | default(foreman_default_organization) | default(omit) }}'
    parameters: '{{ item.parameters | default(foreman_default_parameters) | default(omit) }}'
    provision_method: '{{ item.provision_method | default(foreman_default_provision_method) | default(omit) }}'
    root_pass: '{{ item.root_pass | default(foreman_default_root_pass) | default(omit) }}'
    state: '{{ item.state | default(foreman_default_state) | default(omit) }}'
    subnet: '{{ item.subnet | default(foreman_default_subnet) | default(omit) }}'
    foreman_host: '{{ foreman_host }}'
    foreman_port: '{{ foreman_port }}'
    foreman_user: '{{ foreman_user }}'
    foreman_pass: '{{ foreman_pass }}'
  with_items: foreman_hosts
  register: foreman_host_result

- debug: var=foreman_host_result.results
  when: foreman_debug
