---
- include: organization.yml
  when: foreman_organizations is defined

- include: architecture.yml
  when: foreman_architectures is defined

- include: compute_profile.yml
  when: foreman_compute_profiles is defined

- include: compute_resource.yml
  when: foreman_compute_resources is defined

- include: compute_attribute.yml
  when: foreman_compute_attributes is defined

- include: domain.yml
  when: foreman_domains is defined

- include: environment.yml
  when: foreman_environments is defined

- include: location.yml
  when: foreman_locations is defined

- include: hostgroup.yml
  when: foreman_hostgroups is defined

- include: subnet.yml
  when: foreman_subnets is defined

- include: smart_proxy.yml
  when: foreman_smart_proxies is defined

- include: host.yml
  when: foreman_hosts is defined