---
- include: architecture.yml
  when: foreman_architectures is defined

- include: compute_profile.yml
  when: foreman_compute_profiles is defined

- include: compute_resource.yml
  when: foreman_compute_resources is defined

- include: domain.yml
  when: foreman_domains is defined

- include: environment.yml
  tags: foreman_environments.yml is defined

- include: hostgroup.yml
  when: foreman_hostgroups is defined

- include: host.yml
  when: foreman_hosts is defined