---
- name: Ensure Operatingsystem
  foreman_operatingsystem:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    architectures: '{{ item.architectures | default() }}'
    description: '{{ item.description | default() }}'
    family: '{{ item.family | default() }}'
    major: '{{ item.major }}'
    media: '{{ item.media | default() }}'
    minor: '{{ item.minor | default() }}'
    partition_tables: '{{ item.partition_tables | default() }}'
    release_name: '{{ item.release_name | default() }}'
    foreman_host: '{{ foreman_host }}'
    foreman_port: '{{ foreman_port }}'
    foreman_user: '{{ foreman_user }}'
    foreman_pass: '{{ foreman_pass }}'
  with_items: foreman_operatingsystems
  tags: foreman_operatingsystem
  register: foreman_operatingsystem_result

- debug: var=foreman_operatingsystem_result.results
  when: foreman_debug
