---
- name: Ensure Role
  foreman_role:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    foreman_host: '{{ foreman_host }}'
    foreman_port: '{{ foreman_port }}'
    foreman_user: '{{ foreman_user }}'
    foreman_pass: '{{ foreman_pass }}'
  with_items: foreman_roles
  tags: foreman_role
  register: foreman_role_result

- debug: var=foreman_role_result.results
  when: foreman_debug
