---
- name: Ensure Smart Proxy
  foreman_smart_proxy:
    name: '{{ item.name }}'
    url: '{{ item.url }}'
    state: '{{ item.state }}'
    foreman_host: '{{ foreman_host }}'
    foreman_port: '{{ foreman_port }}'
    foreman_user: '{{ foreman_user }}'
    foreman_pass: '{{ foreman_pass }}'
  with_items: foreman_smart_proxies
  tags: smart_proxy