---
- name: Ensure subnet
  foreman_subnet:
    name: '{{ item.name }}'
    network: '{{ item.network }}'
    gateway: '{{ item.gateway | default(None) }}'
    dns_primary: '{{ item.dns_primary | default(None) }}'
    dns_secondary: '{{ item.dns_secondary | default(None) }}'
    ipam: '{{ item.ipam | default(None) }}'
    ip_from: '{{ item.ip_from | default(None) }}'
    ip_to: '{{ item.ip_to | default(None) }}'
    vlanid: '{{ item.vlanid | default(None) }}'
    mask: '{{ item.mask }}'
    dhcp_proxy: '{{ item.dhcp_proxy }}'
    dns_proxy: '{{ item.dns_proxy }}'
    tftp_proxy: '{{ item.tftp_proxy }}'
    domains: '{{ item.domains }}'
    state: '{{ item.state }}'
    foreman_host: '{{ foreman_host }}'
    foreman_port: '{{ foreman_port }}'
    foreman_user: '{{ foreman_user }}'
    foreman_pass: '{{ foreman_pass }}'
  with_items: foreman_subnets
  tags: foreman_subnet
  register: foreman_subnet_result

- debug: var=foreman_subnet_result.results
  when: foreman_debug
