---
- name: Ensure User
  foreman_user:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    admin: '{{ item.admin | default("false") }}'
    auth: '{{ item.auth | default("Internal") }}'
    firstname: '{{ item.firstname | default("") }}'
    lastname: '{{ item.lastname | default("") }}'
    mail: '{{ item.mail | default("") }}'
    password: '{{ item.password | default("") }}'
    roles: '{{ item.roles | default([]) }}'
    foreman_host: '{{ foreman_host }}'
    foreman_port: '{{ foreman_port }}'
    foreman_user: '{{ foreman_user }}'
    foreman_pass: '{{ foreman_pass }}'
  with_items: foreman_users
  tags: foreman_user
  register: foreman_user_result

- debug: var=foreman_user_result.results
  when: foreman_debug
